---
title: "Costing for CXR and AI in Nigeria"
author: "Tushar Garg"
date: "`r Sys.Date()`"
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo=F,message=F, warning=F)
suppressMessages(if (!require("pacman")) install.packages("pacman"))
pacman::p_load(tidyverse,rio,janitor,here,scales,sessioninfo)

# load functions
source(here("Functions","function_EAC.R"))
```

```{r session info}
# sessioninfo::session_info(pkgs = c("loaded", "attached")[1], to_file = here("Session info","Costing_Nigeria_session_info.txt"))
```

```{r import, include=F}
# 66 screening events in community camps from 17 July to 6 December 2022.
n_days <- as.numeric(difftime(as.Date("2022-12-06"), as.Date("2022-07-17"), units = "day"))
n_camp <- 66

# Annual Xpert test volume
# Assumption: full utilization = 2 cycles per day on 4 module (Global Fund guidance) for 251 days per annum
n_annualxpert <- 2*4*251

# Total Xpert+ = 85; from main paper
maxdiagnosed <- 85

table3 <- import(here("Data","PaperTable3.xlsx"), which = "Table")

case_finding0 <- table3 %>% 
  clean_names() %>% 
  # calculating number diagnosed in each scenario
  mutate(maxdx = maxdiagnosed) %>% 
  mutate(tb_diagnosed = maxdx - people_with_tb_missed) %>% 
  select(algorithm, tests_used, tb_diagnosed) %>% 
  # Keeping only scenarios to be used for costing
  filter(algorithm %in% c("Cough ≥ 2 weeks", 
                          "Any symptom", 
                          "Abnormality ≥ 0.30", 
                          "Abnormality ≥ 0.30 OR any symptom")) %>% 
  mutate(p_subclinical = if_else(algorithm == "Abnormality ≥ 0.30", 0.0988,NA))

subclin <- import(here("Data","PaperTable3_subclinical.xlsx")) %>% clean_names() %>% select(1:4)

case_finding <- bind_rows(subclin,case_finding0)

cost_input <- import(here("Data","cost_input.xlsx"), which = "cost") %>% 
  clean_names()
```

```{r cost calculation, include=F}
# Define a function to generate summary_table and cost data frames
generate_cost_summary <- function(discount, ely_equipment, ely_training) {
  
  # Annuitized equipment cost
  cost <- cost_input %>%
    rowwise() %>%
    # Annuitizing equipment cost
    mutate(unit_cost = ifelse(description %in% c("X-ray instrument - MinXray TR90BH", 
                                                 "GeneXpert") & !is.na(unit_cost),
                              calculate_eac(discount_rate = discount, asset_price = unit_cost, ELY = ely_equipment),
                              unit_cost)) %>%
    # Annuitizing training cost
    mutate(unit_cost = ifelse(category %in% c("Training") & !is.na(unit_cost),
                              calculate_eac(discount_rate = discount, asset_price = unit_cost, ELY = ely_training),
                              unit_cost)) %>%
    mutate(across(c(unit_cost, quantity, time), as.numeric)) %>% 
    ungroup()
  
  # Create a unique identifier for each algorithm
  case_finding <- case_finding %>% mutate(alg_id = paste0("alg_", row_number()))
  
  # Adjust quantities and calculate costs for each scenario
  for (i in 1:nrow(case_finding)) {
    alg_name <- case_finding$algorithm[i]
    alg_id <- case_finding$alg_id[i]
    tests_used <- case_finding$tests_used[i]
    tb_diagnosed <- case_finding$tb_diagnosed[i]
    
    quantity_col <- paste0("quantity_", alg_id)
    time_col <- paste0("time_", alg_id)
    cost_col <- paste0("cost_", alg_id)
    
    cost[[quantity_col]] <- cost$quantity
    cost[[quantity_col]][cost$description == "Presumptive identified and sample provided"] <- tests_used
    cost[[quantity_col]][cost$description == "Sputum container"] <- tests_used
    cost[[quantity_col]][cost$description == "GeneXpert cartridge"] <- tests_used
    cost[[quantity_col]][cost$description == "Case detected"] <- tb_diagnosed
    
    # Subtract 1 for radiographer only if Cough OR Any symptom algorithms
    if (case_finding$algorithm[i] %in% c("Any symptom", "Cough ≥ 2 weeks")) {
      cost[[quantity_col]][cost$description == "Lung health camp team"] <- 
        cost[[quantity_col]][cost$description == "Lung health camp team"] - 1
    }
    
    # Set quantity to zero for CXR and AI if only Cough OR Any symptom algorithms
    if (case_finding$algorithm[i] %in% c("Any symptom", "Cough ≥ 2 weeks")) {
      cost[[quantity_col]][cost$description %in% c("X-ray instrument - MinXray TR90BH", "AI licence - qure.ai qXR")] <- 0
    }
    
    cost[[time_col]] <- cost$time
    cost[[time_col]][cost$description == "GeneXpert"] <- tests_used / (n_annualxpert + tests_used)
    
    # Calculate cost for each scenario
    cost[[cost_col]] <- ceiling(cost[[quantity_col]] * cost$unit_cost * cost[[time_col]])
  }
  
  # Calculate total cost for each algorithm
  total_cost <- cost %>%
    summarise(across(starts_with("cost_"), ~ sum(.x, na.rm = TRUE))) %>%
    pivot_longer(cols = everything(), names_to = "cost_col", values_to = "total_cost") %>%
    mutate(
      alg_id = gsub("cost_", "", cost_col)
    )
  
  # Create a summary table with tests_used and tb_diagnosed from case_finding
  summary_table <- case_finding %>% 
    left_join(total_cost, by = "alg_id") %>% 
    mutate(cost_per_tb_dx = total_cost / tb_diagnosed) %>% 
    mutate(across(where(is.numeric), round, 2)) %>%
    rename(
      Algorithm = algorithm,
      `Tests used` = tests_used,
      `TB Diagnosed` = tb_diagnosed,
      `Total Cost` = total_cost,
      `Cost per case diagnosed` = cost_per_tb_dx
    )
  
  list(summary_table = summary_table, cost = cost)
}

```

```{r summary, include=F}
result_ely5 <- generate_cost_summary(discount = 0.03, ely_equipment = 5, ely_training = 2)
summary_ely5 <- result_ely5$summary_table %>% select(-c(alg_id,cost_col))


summary_ely5_cxr <- summary_ely5 %>% 
  filter(Algorithm == "Abnormality ≥ 0.30")
```

```{r plot}
algorithms_to_plot <- summary_ely5 %>% 
  filter(Algorithm != "Abnormality ≥ 0.30",
         Algorithm != "Cough ≥ 2 weeks")

summary_ely5_cxr %>% 
  ggplot(aes(x = p_subclinical, y = `Cost per case diagnosed`)) +
  geom_line(size = 0.65, linetype = "solid", color = "#708090") +
  geom_point(size = 1.5, shape = 16, color = "#0072B2") +
  geom_hline(data = algorithms_to_plot, aes(yintercept = `Cost per case diagnosed`, color = Algorithm), linetype = "dashed") +
  labs(
    # title = "Modeled cost per TB case diagnosed for Abnormality ≥ 0.30 algorithm",
    # caption = "Annotations show cost per case detected for different scenario from the main analysis."
    x = "Proportion of asymptomatic TB",
    y = "Cost per case diagnosed (US$)"
  ) +
  annotate("text", 
           x = max(summary_ely5_cxr$p_subclinical), 
           y = algorithms_to_plot$`Cost per case diagnosed`, 
           label = paste(algorithms_to_plot$Algorithm, "=", dollar(round(algorithms_to_plot$`Cost per case diagnosed`, 0))), 
           vjust = -1, hjust = 1, color = "black", size = 3, family = "Helvetica") +
  scale_x_continuous(labels = percent_format(accuracy = 1), limits = c(0, NA)) +  
  scale_y_continuous(labels = dollar_format(), breaks = pretty_breaks(n = 4)) +  
  scale_color_manual(values = c("#1b9e77", "#d85f02")) +  
  theme_minimal(base_family = "Helvetica") +
  theme(
    legend.position = "none",  
    legend.title = element_blank(), 
    plot.caption = element_text(size = 10, hjust = 0)  
  )

ggsave(here("Output","Plot","cost_subclinical.jpg"), plot = last_plot(), width = 9, height = 6, dpi = 600)
```

